# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='garb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=300)),
                ('cord_x', models.IntegerField(default=0)),
                ('cord_y', models.IntegerField(default=0)),
            ],
        ),
    ]
