# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='garb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('ident', models.IntegerField(default=0)),
                ('cord_x', models.IntegerField(default=0)),
                ('cord_y', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('json', models.TextField()),
                ('res_file_name_m', models.TextField(default=b'-')),
                ('res_file_name_f', models.TextField(default=b'-')),
            ],
        ),
    ]
