# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_garb_ident'),
    ]

    operations = [
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('city', models.CharField(max_length=200)),
                ('json_file_name', models.CharField(max_length=100)),
            ],
        ),
    ]
