# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(),
        ),
    ]
