# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20171112_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='json',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
