# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_request_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='json_file_name',
            new_name='res_file_name',
        ),
    ]
